### PR TITLE
fix: prevent join/leave events from firing when muting

### LINKED ISSUE #7: Slack sends a join/leave message whenever the user mutes and unmutes themselves

### PR DESCRIPTION
**Pull request by ed1621**
fix #7

### CODE REVIEW

File: src/discord/handle-voice-state-update.ts [hunk 1]
```diff
@@ -27,7 +27,7 @@ export default function handleVoiceState(oldState: VoiceState, newState: VoiceSt
     return
   }
 
-  if (newChannelIsDiscordAudioChannel) {
+  if (newChannelIsDiscordAudioChannel && newChannelIsDiscordAudioChannel !== oldChannelIsDiscordAudioChannel) {
```
Comment (BuiltByWalsh) [inline src/discord/handle-voice-state-update.ts]: What if we stored this in a variable for both if statements called `channelHasNotChanged`

**Review by BuiltByWalsh — CHANGES_REQUESTED** [review]

File: src/discord/handle-voice-state-update.ts (hunk 1 above)
Comment (ed1621) [reply src/discord/handle-voice-state-update.ts]: 👍 i'll do that real quick

**Review by BuiltByWalsh — APPROVED** [review]
